### ISSUE TITLE
Support optionally printing parameter names

### ISSUE THREAD

**Issue by sirthias** [com-lihaoyi/PPrint#4]
It'd be awesome if pprint also supported rendering of parameter names.

E.g., an instance of type

```scala
case class Color(red: Byte, green: Byte, blue: Byte)
```

could be rendered as

```
Color(red = 10, green = 20, blue = 30)
```

instead of

```
Color(10, 20, 30)
```

**Comment by lihaoyi** [comment]
Seems reasonable. Might not be able to support this in Scala.js, since it would require runtime reflection on case classes to "guess" which fields have what names, but I could imagine it working. If anyone wants to give it a try feel free!

**Comment by sirthias** [comment]
Would it be possible to offload this capturing of field names to the compiler rather than runtime reflection? It appears like it should be possible via a macro...

**Comment by lihaoyi** [comment]
Not anymore; the big change in pprint 0.5.0 is we no longer use implicits/macros at all. They were pretty unreliable, and resulted in a whole bunch of issues with Ammonite where they blew up or behaved badly when presented with odd types. 

From 0.5.0, `pprint` takes an `Any`, which means there really isn't much you can do with it at compile time and have to wait until runtime to inspect what value you got

**Comment by sirthias** [comment]
Ok, thank you for this clarification!

**Comment by SethTisue** [comment]
scala/scala#6972 was merged, so maybe there's hope for this now on Scala 2.13?

**Comment by mpgirro** [comment]
I would very much appreciate this feature too!

**Comment by vidma** [comment]
yup, IMHO for `scala 2.13` productElementNames should yield a pretty neat and simple solution.

---

here my current `pprint` customization for `scala 2.11+` by adding additional handlers to pprint, e.g.:

for:
```scala
  pprint2 = pprint.copy(additionalHandlers = pprintAdditionalHandlers)

  case class Author(firstName: String, lastName: String)
  case class Book(isbn: String, author: Author)
  val b = Book("978-0486282114", Author("first", "last"))
  pprint2.pprintln(b)
```

it prints:
<img width="636" alt="Screenshot 2019-07-17 at 19 40 36" src="https://user-images.githubusercontent.com/213426/61394081-0c516880-a8cb-11e9-97b2-74f372e7d9af.png">


for code, see https://stackoverflow.com/a/57080463/1276782

for scala 2.11 currently I use plain java reflection to get all class fields & check if a field value exists inside case class (i.e.  `product.productIterator.toSet.contains(value)` ) - yes slightly hacky, but 
works very well, at least in a non-prod environment for tests/info.
