### ISSUE TITLE
Unicode printout possible?

### ISSUE THREAD

**Issue by hartmut27** [com-lihaoyi/PPrint#42]
```
println("SCALA: «values»")
pprint.pprintln("PPRINT: «values»")
```
prints to my console
```
SCALA: «values»
"PPRINT: \u00abvalues\u00bb"
```
is there a way that I could receive
```
"PPRINT: «values»"
```
instead? 
(using version 0.6 of PPrint)

**Comment by pharod** [comment]
@lihaoyi Just bumped in same issue - took me awhile to understand I don't need to unescape unicode chars, its just library prints this way. Would be nice to see this fix merged into library.

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/PPrint/pull/71
