### ISSUE TITLE
Change color in the customization

### ISSUE THREAD

**Issue by oneengineer** [com-lihaoyi/PPrint#51]
This is the example code in guide.
```
  pprint.copy(
    additionalHandlers = { 
      case value: Double =>  pprint.Tree.Literal(f"$value%1.5f") /* 5 digit precision */ 
    }
  ) 
```

Is it possible to change color in the customized handler?

**Comment by lihaoyi** [comment]
This can already be customized via `colorLiteral` and `colorApplyPrefix`
